[package]
name = "trace-desktop"
description = "TRACE desktop composition root"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "trace_desktop"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "trace"
path = "src/main.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
base64 = "0.22.1"
serde.workspace = true
serde_json = "1.0.145"
tauri.workspace = true
tauri-plugin-dialog = "2.7.2"
time.workspace = true
trace-ac = { path = "../../../crates/trace-ac" }
trace-adapter = { path = "../../../crates/trace-adapter" }
trace-core = { version = "0.1.0", path = "../../../crates/trace-core" }
trace-domain.workspace = true
trace-recorder = { path = "../../../crates/trace-recorder" }
trace-storage = { path = "../../../crates/trace-storage" }

[lints]
workspace = true
