[package]
name = "trace-ac"
description = "Assetto Corsa telemetry adapter for TRACE"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
trace-adapter = { path = "../trace-adapter" }
trace-domain.workspace = true
trace-windows-shmem = { path = "../trace-windows-shmem" }

[lints]
workspace = true
